# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0015_auto_20180304_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='static/case-studies/images/%Y/%m/%d/')),
                ('doc', models.FileField(upload_to='static/case-studies/doc/%Y/%m/%d/')),
            ],
        ),
    ]
