# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0019_auto_20190821_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudies',
            old_name='title',
            new_name='name',
        ),
    ]
