# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0020_auto_20190821_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudies',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='casestudies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/%Y/%m/%d/'),
        ),
    ]
